name: Generate Word of the Day

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3 AM (UTC)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Generate API Route
        run: |
          curl -X GET "https://lexical-word.vercel.app/api/word/generate"
